# Generated by Django 4.2.11 on 2024-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='crew',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='musician',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='CrewMember',
        ),
    ]
